# Site settings
title: jon silvers marketing geek and wannabe dev
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Jon Silvers learns how to create a site in jekyll and github.
baseurl: "/me" # the subpath of your site, e.g. /blog/
url: "http://jsilvers.github.io" # the base hostname & protocol for your site
twitter_username: jonsilvers
github_username:  jsilvers

# Build settings
markdown: kramdown
